name: Luarocks Upload

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    name: Luarocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: Show diagnostics that are not visible in current view
          detailed_description: |
            sense.nvim shows diagnostics that are not visible in current view with their distance.
            Allows you to quickly navigate to off-screen diagnostics with relative-line-number motions.
            Don't miss the diagnostics ever again!
          dependencies: |
            luautf8
          test_dependencies: |
            nlua
          copy_directories: |
            {{ neovim.plugin.dirs }}
